name: deploy-pages

on:
  push:
    branches:
      - 'gh-pages'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    needs: read
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: configure pages
        uses: actions/configure-pages@v2
      - name: upload pages build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v1